#!/usr/bin/env bash
_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export OMNISCI_IMAGE=${OMNISCI_IMAGE:="$(awk -F '[ :]' '{print $2}' "${_DIR}/Dockerfile")"}
export OMNISCI_IMAGE_VERSION=${OMNISCI_IMAGE_VERSION:="$(awk -F '[ :]' '{print $3}' "${_DIR}/Dockerfile")"}
export OMNISCI_ROOT=${OMNISCI_ROOT:="$DOKKU_LIB_ROOT/services/omnisci"}
export OMNISCI_HOST_ROOT=${OMNISCI_HOST_ROOT:=$OMNISCI_ROOT}

export PLUGIN_UNIMPLEMENTED_SUBCOMMANDS=("backup" "backup-auth" "backup-deauth" "backup-schedule" "backup-schedule-cat" "backup-set-encryption" "backup-unschedule" "backup-unset-encryption" "clone" "export" "import")
export PLUGIN_COMMAND_PREFIX="omnisci"
export PLUGIN_CONFIG_ROOT=${PLUGIN_CONFIG_ROOT:="$DOKKU_LIB_ROOT/config/$PLUGIN_COMMAND_PREFIX"}
export PLUGIN_DATA_ROOT=$OMNISCI_ROOT
export PLUGIN_DATA_HOST_ROOT=$OMNISCI_HOST_ROOT
export PLUGIN_DATASTORE_PORTS=(6274 6278)
export PLUGIN_DATASTORE_WAIT_PORT=6274
export PLUGIN_DEFAULT_ALIAS="OMNISCI"
export PLUGIN_DISABLE_PULL=${OMNISCI_DISABLE_PULL:=}
export PLUGIN_DISABLE_PULL_VARIABLE="OMNISCI_DISABLE_PULL"
export PLUGIN_ALT_ALIAS="DOKKU_OMNISCI"
export PLUGIN_IMAGE=$OMNISCI_IMAGE
export PLUGIN_IMAGE_VERSION=$OMNISCI_IMAGE_VERSION
export PLUGIN_SCHEME="omnisci"
export PLUGIN_SERVICE="Omnisci"
export PLUGIN_VARIABLE="OMNISCI"
export PLUGIN_BASE_PATH="$PLUGIN_PATH"
export PLUGIN_CONFIG_SUFFIX="config"
if [[ -n $DOKKU_API_VERSION ]]; then
  export PLUGIN_BASE_PATH="$PLUGIN_ENABLED_PATH"
fi

export PLUGIN_BUSYBOX_IMAGE="busybox:1.34.1-uclibc"
export PLUGIN_AMBASSADOR_IMAGE="dokku/ambassador:0.5.0"
export PLUGIN_S3BACKUP_IMAGE="dokku/s3backup:0.14.0"
export PLUGIN_WAIT_IMAGE="dokku/wait:0.6.0"

export OMNISCI_CONFIG_OPTIONS=${OMNISCI_CONFIG_OPTIONS:=""}
